# Build stage
FROM node:lts-alpine AS builder

USER node
WORKDIR /home/node

COPY package*.json .
RUN npm ci

COPY --chown=node:node . .
RUN npm run build && npm prune --omit=dev


# Final run stage
FROM node:lts-alpine

ENV NODE_ENV production
# Tambahkan konfigurasi memori untuk Node.js
ENV NODE_OPTIONS="--max-old-space-size=256"
USER node
WORKDIR /home/node

COPY --from=builder --chown=node:node /home/node/package*.json .
COPY --from=builder --chown=node:node /home/node/node_modules ./node_modules
COPY --from=builder --chown=node:node /home/node/dist ./dist

ARG PORT
EXPOSE ${PORT:-3001}

# Gunakan node dengan flag untuk memory
CMD ["node", "--optimize-for-size", "--gc-interval=100", "dist/main.js"]
